name: JCMS website build

on: [push]

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '>= 3.10'

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.8.5'
          enable-cache: true

      - name: Install dependencies
        run: uv sync
      
      - name: Build
        run: uv run build.py
      
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
      
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
